SimpleNoteSaver/Controllers/NotesController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SimpleNoteSaver.Data;
using SimpleNoteSaver.Models;
using SimpleNoteSaver.Repositories;

namespace SimpleNoteSaver.Controllers
{
    public class NotesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IUsersRepository _userServices;
        private readonly INotesRepository _noteServices;

        public NotesController(ApplicationDbContext context, IUsersRepository userServices, INotesRepository noteServices)
        {
            _context = context;
            _userServices = userServices;
            _noteServices = noteServices;
        }


        public async Task<IActionResult> Index()
        {
            var currentUser = await _userServices.GetCurrentUser(this.User);
            var notes = await _noteServices.GetNotes(currentUser.Id);
            return View(notes);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var note = await _noteServices.GetOneNote(id ?? default);

            if (note == null)
            {
                return NotFound();
            }

            return View(note);
        }

        [HttpGet]
        public async Task<IActionResult> CreateAsync()
        {
            var currentUser = await _userServices.GetCurrentUser(this.User);
            ViewData["UserId"] = currentUser.Id;
            ViewData["Mode"] = "create";
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,UserId")] Notes note)
        {
            if (!(await _userServices.ValidateUserId(note.UserId, this.User)) ) return Unauthorized();

            if (ModelState.IsValid)
            {
                await _noteServices.CreateNote(note);
                return RedirectToAction(nameof(Index));
            }
            else 
            {
                return View(note);
            }
            
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var note = await _context.Note.FindAsync(id);
            if (note == null)
            {
                return NotFound();
            }

            var currentUser = await _userServices.GetCurrentUser(this.User);
            ViewData["UserId"] = currentUser.Id;
            ViewData["Mode"] = "edit";
            return View("Create", note);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description,UserId")] Notes note)
        {
            if (id != note.Id)
            {
                return NotFound();
            }

            if (!(await _userServices.ValidateUserId(note.UserId, this.User))) return Unauthorized();

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(note);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (_noteServices.NoteExists(note.Id) == false)
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            var currentUser = await _userServices.GetCurrentUser(this.User);
            ViewData["UserId"] = currentUser.Id;
            return View(note);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var note = await _noteServices.GetOneNote(id ?? default);

            if (note == null)
            {
                return NotFound();
            }

            return View(note);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            
            var note = await _context.Note.FindAsync(id);

            if (await _userServices.ValidateUserId(note.UserId, this.User)) 
            {
                await _noteServices.DeleteNote(note);
                return RedirectToAction(nameof(Index));
            }
            else 
            {
                return Unauthorized();
            }
            
        }

    }
}

SimpleNoteSaver/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SimpleNoteSaver</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css" integrity="sha384-Bfad6CLCknfcloXFOyFnlgtENryhrpZCe29RTifKEixXQZ38WheV+i/6YWSzkz3V" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SimpleNoteSaver</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Notes" asp-action="Index">Notes Saved<i class="fas fa-book px-2"></i></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Notes" asp-action="Create">Create new one<i class="fas fa-sticky-note px-2"></i></a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Home" asp-action="About">About me</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container d-flex flex-wrap">
            &copy; 2020 - SimpleNoteSaver - Made with ♡ by reon150
            <a class="btn btn-lg" href="https://github.com/reon150/Simple-Note-Saver" target="_blank" role="button">Source Code<i class="fab fa-github ml-2"></i></a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>